services:
  postgres:
    image: library/postgres
    ports:
      - "5432:5432"
    volumes_from:
      - pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ten_ex

  pgdata:
    image: busybox
    volumes:
      - /data

  redis-app:
    image: redis
    ports:
      - "6379:6379"